com.thoughtworks.xstream.io.StreamException: 
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:124)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:148)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:135)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.hasMoreChildren(AbstractPullReader.java:87)
	at com.intellij.database.model.serialization.FixHierarchicalStreamReader.hasMoreChildren(FixHierarchicalStream.kt)
	at com.intellij.database.model.serialization.ModelImporter.deserializeModel(ModelImporter.java:106)
	at com.intellij.database.model.serialization.ModelSerializerKt.deserialize(ModelSerializer.kt:37)
	at com.intellij.database.model.serialization.ModelSerializerKt.deserialize(ModelSerializer.kt:27)
	at com.intellij.database.dataSource.DataSourceStorage.readModel(DataSourceStorage.java:702)
	at com.intellij.database.dataSource.DataSourceStorage.readModel(DataSourceStorage.java:690)
	at com.intellij.database.dataSource.DataSourceStorage.loadModels(DataSourceStorage.java:506)
	at com.intellij.database.dataSource.DataSourceStorage.access$000(DataSourceStorage.java:92)
	at com.intellij.database.dataSource.DataSourceStorage$2.run(DataSourceStorage.java:407)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.xmlpull.v1.XmlPullParserException: unexpected character in markup < (position: END_TAG seen ...</Collation>\r\n    </schema>\r\n<<... @24:3) 
	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1261)
	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:109)
	... 25 more
